//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EjbAdminServiceServiceSoapBinding", Namespace="http://impl.business.sdi.com/")]
public partial class EjbAdminServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getUsuariosOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUserLoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback getComentariosOperationCompleted;
    
    private System.Threading.SendOrPostCallback deshabilitarUsuarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback eliminarComentarioOperationCompleted;
    
    private System.Threading.SendOrPostCallback getViajesParticipadoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getViajesPromovidoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getDestinoOperationCompleted;
    
    /// <remarks/>
    public EjbAdminServiceService() {
        this.Url = "http://EII-A-LIBRE-09:8280/sdi3-180.EJB/AdminService";
    }
    
    /// <remarks/>
    public event getUsuariosCompletedEventHandler getUsuariosCompleted;
    
    /// <remarks/>
    public event getUserLoginCompletedEventHandler getUserLoginCompleted;
    
    /// <remarks/>
    public event getComentariosCompletedEventHandler getComentariosCompleted;
    
    /// <remarks/>
    public event deshabilitarUsuarioCompletedEventHandler deshabilitarUsuarioCompleted;
    
    /// <remarks/>
    public event eliminarComentarioCompletedEventHandler eliminarComentarioCompleted;
    
    /// <remarks/>
    public event getViajesParticipadoCompletedEventHandler getViajesParticipadoCompleted;
    
    /// <remarks/>
    public event getViajesPromovidoCompletedEventHandler getViajesPromovidoCompleted;
    
    /// <remarks/>
    public event getDestinoCompletedEventHandler getDestinoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user[] getUsuarios() {
        object[] results = this.Invoke("getUsuarios", new object[0]);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUsuarios(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUsuarios", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public user[] EndgetUsuarios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((user[])(results[0]));
    }
    
    /// <remarks/>
    public void getUsuariosAsync() {
        this.getUsuariosAsync(null);
    }
    
    /// <remarks/>
    public void getUsuariosAsync(object userState) {
        if ((this.getUsuariosOperationCompleted == null)) {
            this.getUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsuariosOperationCompleted);
        }
        this.InvokeAsync("getUsuarios", new object[0], this.getUsuariosOperationCompleted, userState);
    }
    
    private void OngetUsuariosOperationCompleted(object arg) {
        if ((this.getUsuariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUsuariosCompleted(this, new getUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getUserLogin([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("getUserLogin", new object[] {
                    arg0,
                    arg0Specified});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetUserLogin(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getUserLogin", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetUserLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getUserLoginAsync(long arg0, bool arg0Specified) {
        this.getUserLoginAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void getUserLoginAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.getUserLoginOperationCompleted == null)) {
            this.getUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserLoginOperationCompleted);
        }
        this.InvokeAsync("getUserLogin", new object[] {
                    arg0,
                    arg0Specified}, this.getUserLoginOperationCompleted, userState);
    }
    
    private void OngetUserLoginOperationCompleted(object arg) {
        if ((this.getUserLoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUserLoginCompleted(this, new getUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rating[] getComentarios() {
        object[] results = this.Invoke("getComentarios", new object[0]);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetComentarios(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getComentarios", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public rating[] EndgetComentarios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((rating[])(results[0]));
    }
    
    /// <remarks/>
    public void getComentariosAsync() {
        this.getComentariosAsync(null);
    }
    
    /// <remarks/>
    public void getComentariosAsync(object userState) {
        if ((this.getComentariosOperationCompleted == null)) {
            this.getComentariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComentariosOperationCompleted);
        }
        this.InvokeAsync("getComentarios", new object[0], this.getComentariosOperationCompleted, userState);
    }
    
    private void OngetComentariosOperationCompleted(object arg) {
        if ((this.getComentariosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getComentariosCompleted(this, new getComentariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void deshabilitarUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("deshabilitarUsuario", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindeshabilitarUsuario(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("deshabilitarUsuario", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddeshabilitarUsuario(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void deshabilitarUsuarioAsync(long arg0, bool arg0Specified) {
        this.deshabilitarUsuarioAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void deshabilitarUsuarioAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.deshabilitarUsuarioOperationCompleted == null)) {
            this.deshabilitarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeshabilitarUsuarioOperationCompleted);
        }
        this.InvokeAsync("deshabilitarUsuario", new object[] {
                    arg0,
                    arg0Specified}, this.deshabilitarUsuarioOperationCompleted, userState);
    }
    
    private void OndeshabilitarUsuarioOperationCompleted(object arg) {
        if ((this.deshabilitarUsuarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deshabilitarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void eliminarComentario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        this.Invoke("eliminarComentario", new object[] {
                    arg0,
                    arg0Specified});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegineliminarComentario(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("eliminarComentario", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndeliminarComentario(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void eliminarComentarioAsync(long arg0, bool arg0Specified) {
        this.eliminarComentarioAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void eliminarComentarioAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.eliminarComentarioOperationCompleted == null)) {
            this.eliminarComentarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarComentarioOperationCompleted);
        }
        this.InvokeAsync("eliminarComentario", new object[] {
                    arg0,
                    arg0Specified}, this.eliminarComentarioOperationCompleted, userState);
    }
    
    private void OneliminarComentarioOperationCompleted(object arg) {
        if ((this.eliminarComentarioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.eliminarComentarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int getViajesParticipado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        object[] results = this.Invoke("getViajesParticipado", new object[] {
                    arg0});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetViajesParticipado(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getViajesParticipado", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndgetViajesParticipado(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void getViajesParticipadoAsync(user arg0) {
        this.getViajesParticipadoAsync(arg0, null);
    }
    
    /// <remarks/>
    public void getViajesParticipadoAsync(user arg0, object userState) {
        if ((this.getViajesParticipadoOperationCompleted == null)) {
            this.getViajesParticipadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViajesParticipadoOperationCompleted);
        }
        this.InvokeAsync("getViajesParticipado", new object[] {
                    arg0}, this.getViajesParticipadoOperationCompleted, userState);
    }
    
    private void OngetViajesParticipadoOperationCompleted(object arg) {
        if ((this.getViajesParticipadoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getViajesParticipadoCompleted(this, new getViajesParticipadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int getViajesPromovido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] user arg0) {
        object[] results = this.Invoke("getViajesPromovido", new object[] {
                    arg0});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetViajesPromovido(user arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getViajesPromovido", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndgetViajesPromovido(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void getViajesPromovidoAsync(user arg0) {
        this.getViajesPromovidoAsync(arg0, null);
    }
    
    /// <remarks/>
    public void getViajesPromovidoAsync(user arg0, object userState) {
        if ((this.getViajesPromovidoOperationCompleted == null)) {
            this.getViajesPromovidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetViajesPromovidoOperationCompleted);
        }
        this.InvokeAsync("getViajesPromovido", new object[] {
                    arg0}, this.getViajesPromovidoOperationCompleted, userState);
    }
    
    private void OngetViajesPromovidoOperationCompleted(object arg) {
        if ((this.getViajesPromovidoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getViajesPromovidoCompleted(this, new getViajesPromovidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.business.sdi.com/", ResponseNamespace="http://impl.business.sdi.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getDestino([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool arg0Specified) {
        object[] results = this.Invoke("getDestino", new object[] {
                    arg0,
                    arg0Specified});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetDestino(long arg0, bool arg0Specified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getDestino", new object[] {
                    arg0,
                    arg0Specified}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetDestino(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getDestinoAsync(long arg0, bool arg0Specified) {
        this.getDestinoAsync(arg0, arg0Specified, null);
    }
    
    /// <remarks/>
    public void getDestinoAsync(long arg0, bool arg0Specified, object userState) {
        if ((this.getDestinoOperationCompleted == null)) {
            this.getDestinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDestinoOperationCompleted);
        }
        this.InvokeAsync("getDestino", new object[] {
                    arg0,
                    arg0Specified}, this.getDestinoOperationCompleted, userState);
    }
    
    private void OngetDestinoOperationCompleted(object arg) {
        if ((this.getDestinoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getDestinoCompleted(this, new getDestinoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class user {
    
    private string emailField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string loginField;
    
    private string nameField;
    
    private string passwordField;
    
    private userStatus statusField;
    
    private bool statusFieldSpecified;
    
    private string surnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public userStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public enum userStatus {
    
    /// <remarks/>
    ACTIVE,
    
    /// <remarks/>
    CANCELLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.business.sdi.com/")]
public partial class rating {
    
    private string commentField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private long seatAboutTripIdField;
    
    private bool seatAboutTripIdFieldSpecified;
    
    private long seatAboutUserIdField;
    
    private bool seatAboutUserIdFieldSpecified;
    
    private long seatFromTripIdField;
    
    private bool seatFromTripIdFieldSpecified;
    
    private long seatFromUserIdField;
    
    private bool seatFromUserIdFieldSpecified;
    
    private int valueField;
    
    private bool valueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutTripId {
        get {
            return this.seatAboutTripIdField;
        }
        set {
            this.seatAboutTripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutTripIdSpecified {
        get {
            return this.seatAboutTripIdFieldSpecified;
        }
        set {
            this.seatAboutTripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatAboutUserId {
        get {
            return this.seatAboutUserIdField;
        }
        set {
            this.seatAboutUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatAboutUserIdSpecified {
        get {
            return this.seatAboutUserIdFieldSpecified;
        }
        set {
            this.seatAboutUserIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromTripId {
        get {
            return this.seatFromTripIdField;
        }
        set {
            this.seatFromTripIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromTripIdSpecified {
        get {
            return this.seatFromTripIdFieldSpecified;
        }
        set {
            this.seatFromTripIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long seatFromUserId {
        get {
            return this.seatFromUserIdField;
        }
        set {
            this.seatFromUserIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seatFromUserIdSpecified {
        get {
            return this.seatFromUserIdFieldSpecified;
        }
        set {
            this.seatFromUserIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getUsuariosCompletedEventHandler(object sender, getUsuariosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public user[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((user[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getUserLoginCompletedEventHandler(object sender, getUserLoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getComentariosCompletedEventHandler(object sender, getComentariosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getComentariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getComentariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public rating[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((rating[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void deshabilitarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void eliminarComentarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getViajesParticipadoCompletedEventHandler(object sender, getViajesParticipadoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getViajesParticipadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getViajesParticipadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getViajesPromovidoCompletedEventHandler(object sender, getViajesPromovidoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getViajesPromovidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getViajesPromovidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getDestinoCompletedEventHandler(object sender, getDestinoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getDestinoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getDestinoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
